template = "https://github.com/giellalt/template-lang-und"
rev_id = 346
template_sha = "f98c2a37b9866895a157f22bea282f596e7a321a"

[replacements]
__GLOTTOLOG_ID__ = "wayo1238"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayoró"
__UND__ = "wyr"
