template = "https://github.com/giellalt/template-lang-und"
rev_id = 305
template_sha = "64df68fecb78cef7f709bfe67c09affe7c3b0c38"

[replacements]
__GLOTTOLOG_ID__ = "wayo1238"
__LICENSE__ = "GPLv3"
__REPO__ = "lang-wyr"
__UND2C__ = "wyr"
__UNDEFINED__ = "Wayoró"
__UND__ = "wyr"
